name: Generate Sitemap Daily

on:
  push:
    branches:
      - main     # 👈 change if your default branch is different
  schedule:
    - cron: "0 0 * * *"  # 🕛 Runs every day at midnight UTC
  workflow_dispatch:      # optional: lets you trigger it manually too

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate sitemap
        run: npm run next-sitemap
